// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by:
//        'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator'
//
//    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

public static class GdkPlatformSettings
{
#if UNITY_GAMECORE_XBOXONE
    public static string gameConfigTitleId = "7843d472";
    public static string gameConfigScid = "00000000-0000-0000-0000-00007843d472";
    public static string gameConfigSandbox = "";
#elif UNITY_GAMECORE_XBOXSERIES
    public static string gameConfigTitleId = "6ec8d58d";
    public static string gameConfigScid = "00000000-0000-0000-0000-00006ec8d58d";
    public static string gameConfigSandbox = "";
#else
    public static string gameConfigTitleId = "604a0fc7";
    public static string gameConfigScid = "00000000-0000-0000-0000-0000604a0fc7";
    public static string gameConfigSandbox = "";
#endif
}
